title: Kyle Garsuta
author: Kyle Garsuta
description: Professional portfolio of Kyle Garsuta
baseurl: ""
url: https://kgarsuta.com
profile_image_location: /assets/images/profile-image.png
linkedin_username: kgarsuta

# Build settings
permalink: :title

exclude:
  - Gemfile
  - Gemfile.lock
